//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.Report.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PPMSEntities : DbContext
    {
        public PPMSEntities()
            : base("name=PPMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblM_AccountingPeriod> tblM_AccountingPeriod { get; set; }
        public virtual DbSet<tblM_CheckrollPeriod> tblM_CheckrollPeriod { get; set; }
    
        public virtual ObjectResult<SPS_CETAK_BKMHK_Result> SPS_CETAK_BKMHK(Nullable<System.DateTime> bkmDate, string division, string gangCode)
        {
            var bkmDateParameter = bkmDate.HasValue ?
                new ObjectParameter("BkmDate", bkmDate) :
                new ObjectParameter("BkmDate", typeof(System.DateTime));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            var gangCodeParameter = gangCode != null ?
                new ObjectParameter("GangCode", gangCode) :
                new ObjectParameter("GangCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_CETAK_BKMHK_Result>("SPS_CETAK_BKMHK", bkmDateParameter, divisionParameter, gangCodeParameter);
        }
    
        public virtual ObjectResult<SPS_CETAK_BKMHK_DETAIL_DDT_Result> SPS_CETAK_BKMHK_DETAIL_DDT(Nullable<System.DateTime> bkmDate, string division, string gangCode)
        {
            var bkmDateParameter = bkmDate.HasValue ?
                new ObjectParameter("BkmDate", bkmDate) :
                new ObjectParameter("BkmDate", typeof(System.DateTime));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            var gangCodeParameter = gangCode != null ?
                new ObjectParameter("GangCode", gangCode) :
                new ObjectParameter("GangCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_CETAK_BKMHK_DETAIL_DDT_Result>("SPS_CETAK_BKMHK_DETAIL_DDT", bkmDateParameter, divisionParameter, gangCodeParameter);
        }
    
        public virtual ObjectResult<SPS_Cetak_BukuPanenItem_Result> SPS_Cetak_BukuPanenItem(Nullable<System.DateTime> harvestDate, string location, string division, string gang, Nullable<int> crop, string achievement)
        {
            var harvestDateParameter = harvestDate.HasValue ?
                new ObjectParameter("HarvestDate", harvestDate) :
                new ObjectParameter("HarvestDate", typeof(System.DateTime));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            var cropParameter = crop.HasValue ?
                new ObjectParameter("Crop", crop) :
                new ObjectParameter("Crop", typeof(int));
    
            var achievementParameter = achievement != null ?
                new ObjectParameter("Achievement", achievement) :
                new ObjectParameter("Achievement", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_Cetak_BukuPanenItem_Result>("SPS_Cetak_BukuPanenItem", harvestDateParameter, locationParameter, divisionParameter, gangParameter, cropParameter, achievementParameter);
        }
    
        public virtual ObjectResult<SPS_Cetak_BukuPanenItem_Quality_Result> SPS_Cetak_BukuPanenItem_Quality(Nullable<System.DateTime> harvestDate, string location, string division, string gang, Nullable<int> crop, string quality)
        {
            var harvestDateParameter = harvestDate.HasValue ?
                new ObjectParameter("HarvestDate", harvestDate) :
                new ObjectParameter("HarvestDate", typeof(System.DateTime));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            var cropParameter = crop.HasValue ?
                new ObjectParameter("Crop", crop) :
                new ObjectParameter("Crop", typeof(int));
    
            var qualityParameter = quality != null ?
                new ObjectParameter("Quality", quality) :
                new ObjectParameter("Quality", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_Cetak_BukuPanenItem_Quality_Result>("SPS_Cetak_BukuPanenItem_Quality", harvestDateParameter, locationParameter, divisionParameter, gangParameter, cropParameter, qualityParameter);
        }
    
        public virtual ObjectResult<SPS_CETAK_BKMHK_DETAIL_Result> SPS_CETAK_BKMHK_DETAIL(Nullable<System.DateTime> bkmDate, string division, string gangCode)
        {
            var bkmDateParameter = bkmDate.HasValue ?
                new ObjectParameter("BkmDate", bkmDate) :
                new ObjectParameter("BkmDate", typeof(System.DateTime));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            var gangCodeParameter = gangCode != null ?
                new ObjectParameter("GangCode", gangCode) :
                new ObjectParameter("GangCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_CETAK_BKMHK_DETAIL_Result>("SPS_CETAK_BKMHK_DETAIL", bkmDateParameter, divisionParameter, gangCodeParameter);
        }
    
        public virtual ObjectResult<SPS_CETAK_BUKUPANEN_HEADER_REV1_Result> SPS_CETAK_BUKUPANEN_HEADER_REV1(Nullable<System.DateTime> harvestDate, string division, string gang)
        {
            var harvestDateParameter = harvestDate.HasValue ?
                new ObjectParameter("HarvestDate", harvestDate) :
                new ObjectParameter("HarvestDate", typeof(System.DateTime));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_CETAK_BUKUPANEN_HEADER_REV1_Result>("SPS_CETAK_BUKUPANEN_HEADER_REV1", harvestDateParameter, divisionParameter, gangParameter);
        }
    
        public virtual ObjectResult<SPS_Cetak_BukuPanenItem_Rev1_Result> SPS_Cetak_BukuPanenItem_Rev1(Nullable<System.DateTime> harvestDate, string division, string gang, Nullable<int> crop, string achievement)
        {
            var harvestDateParameter = harvestDate.HasValue ?
                new ObjectParameter("HarvestDate", harvestDate) :
                new ObjectParameter("HarvestDate", typeof(System.DateTime));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            var cropParameter = crop.HasValue ?
                new ObjectParameter("Crop", crop) :
                new ObjectParameter("Crop", typeof(int));
    
            var achievementParameter = achievement != null ?
                new ObjectParameter("Achievement", achievement) :
                new ObjectParameter("Achievement", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_Cetak_BukuPanenItem_Rev1_Result>("SPS_Cetak_BukuPanenItem_Rev1", harvestDateParameter, divisionParameter, gangParameter, cropParameter, achievementParameter);
        }
    
        public virtual ObjectResult<GetBukuPanenItemNormal_Result> GetBukuPanenItemNormal(string nik, Nullable<System.DateTime> harvestDate, string location, string crop, string achievement, string gang)
        {
            var nikParameter = nik != null ?
                new ObjectParameter("Nik", nik) :
                new ObjectParameter("Nik", typeof(string));
    
            var harvestDateParameter = harvestDate.HasValue ?
                new ObjectParameter("HarvestDate", harvestDate) :
                new ObjectParameter("HarvestDate", typeof(System.DateTime));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var cropParameter = crop != null ?
                new ObjectParameter("Crop", crop) :
                new ObjectParameter("Crop", typeof(string));
    
            var achievementParameter = achievement != null ?
                new ObjectParameter("Achievement", achievement) :
                new ObjectParameter("Achievement", typeof(string));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBukuPanenItemNormal_Result>("GetBukuPanenItemNormal", nikParameter, harvestDateParameter, locationParameter, cropParameter, achievementParameter, gangParameter);
        }
    
        public virtual ObjectResult<GetBukuPanenItemPenalty_Result> GetBukuPanenItemPenalty(string nik, Nullable<System.DateTime> harvestDate, string location, string crop, string achievement, string gang)
        {
            var nikParameter = nik != null ?
                new ObjectParameter("Nik", nik) :
                new ObjectParameter("Nik", typeof(string));
    
            var harvestDateParameter = harvestDate.HasValue ?
                new ObjectParameter("HarvestDate", harvestDate) :
                new ObjectParameter("HarvestDate", typeof(System.DateTime));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var cropParameter = crop != null ?
                new ObjectParameter("Crop", crop) :
                new ObjectParameter("Crop", typeof(string));
    
            var achievementParameter = achievement != null ?
                new ObjectParameter("Achievement", achievement) :
                new ObjectParameter("Achievement", typeof(string));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBukuPanenItemPenalty_Result>("GetBukuPanenItemPenalty", nikParameter, harvestDateParameter, locationParameter, cropParameter, achievementParameter, gangParameter);
        }
    
        public virtual ObjectResult<SPS_POTONGBUAH_HDR_Result> SPS_POTONGBUAH_HDR(Nullable<System.DateTime> start, Nullable<System.DateTime> finish, string gang, string nik)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var finishParameter = finish.HasValue ?
                new ObjectParameter("Finish", finish) :
                new ObjectParameter("Finish", typeof(System.DateTime));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            var nikParameter = nik != null ?
                new ObjectParameter("Nik", nik) :
                new ObjectParameter("Nik", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_POTONGBUAH_HDR_Result>("SPS_POTONGBUAH_HDR", startParameter, finishParameter, gangParameter, nikParameter);
        }
    
        public virtual ObjectResult<SP_PrestasiOuputHKDivisi_Result> SP_PrestasiOuputHKDivisi(string divisi, Nullable<System.DateTime> bkmdate)
        {
            var divisiParameter = divisi != null ?
                new ObjectParameter("divisi", divisi) :
                new ObjectParameter("divisi", typeof(string));
    
            var bkmdateParameter = bkmdate.HasValue ?
                new ObjectParameter("bkmdate", bkmdate) :
                new ObjectParameter("bkmdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PrestasiOuputHKDivisi_Result>("SP_PrestasiOuputHKDivisi", divisiParameter, bkmdateParameter);
        }
    
        public virtual ObjectResult<SPS_REPORT_ANOMALI_Result> SPS_REPORT_ANOMALI(Nullable<System.DateTime> date, string division)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_REPORT_ANOMALI_Result>("SPS_REPORT_ANOMALI", dateParameter, divisionParameter);
        }
    
        public virtual ObjectResult<SPS_REPORTANOMALIPANENVSANGKUT_Result> SPS_REPORTANOMALIPANENVSANGKUT(Nullable<System.DateTime> start, Nullable<System.DateTime> finish, string block, string estate)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var finishParameter = finish.HasValue ?
                new ObjectParameter("Finish", finish) :
                new ObjectParameter("Finish", typeof(System.DateTime));
    
            var blockParameter = block != null ?
                new ObjectParameter("Block", block) :
                new ObjectParameter("Block", typeof(string));
    
            var estateParameter = estate != null ?
                new ObjectParameter("Estate", estate) :
                new ObjectParameter("Estate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_REPORTANOMALIPANENVSANGKUT_Result>("SPS_REPORTANOMALIPANENVSANGKUT", startParameter, finishParameter, blockParameter, estateParameter);
        }
    
        public virtual ObjectResult<spReport_Cetak_BKM_HK_Result> spReport_Cetak_BKM_HK(string estate, Nullable<System.DateTime> bkmDate, string division, string gangCode)
        {
            var estateParameter = estate != null ?
                new ObjectParameter("estate", estate) :
                new ObjectParameter("estate", typeof(string));
    
            var bkmDateParameter = bkmDate.HasValue ?
                new ObjectParameter("BkmDate", bkmDate) :
                new ObjectParameter("BkmDate", typeof(System.DateTime));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            var gangCodeParameter = gangCode != null ?
                new ObjectParameter("GangCode", gangCode) :
                new ObjectParameter("GangCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReport_Cetak_BKM_HK_Result>("spReport_Cetak_BKM_HK", estateParameter, bkmDateParameter, divisionParameter, gangCodeParameter);
        }
    
        public virtual ObjectResult<spReport_CETAK_BKMHK_DETAIL_Online_Result> spReport_CETAK_BKMHK_DETAIL_Online(string eSTATE, Nullable<System.DateTime> bKM_DATE, string dIVISION, string gANG)
        {
            var eSTATEParameter = eSTATE != null ?
                new ObjectParameter("ESTATE", eSTATE) :
                new ObjectParameter("ESTATE", typeof(string));
    
            var bKM_DATEParameter = bKM_DATE.HasValue ?
                new ObjectParameter("BKM_DATE", bKM_DATE) :
                new ObjectParameter("BKM_DATE", typeof(System.DateTime));
    
            var dIVISIONParameter = dIVISION != null ?
                new ObjectParameter("DIVISION", dIVISION) :
                new ObjectParameter("DIVISION", typeof(string));
    
            var gANGParameter = gANG != null ?
                new ObjectParameter("GANG", gANG) :
                new ObjectParameter("GANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReport_CETAK_BKMHK_DETAIL_Online_Result>("spReport_CETAK_BKMHK_DETAIL_Online", eSTATEParameter, bKM_DATEParameter, dIVISIONParameter, gANGParameter);
        }
    
        public virtual ObjectResult<spReport_Cetak_BukuPanenItem_Rev1_Result> spReport_Cetak_BukuPanenItem_Rev1(string estate, Nullable<System.DateTime> harvestDate, string division, string gang, Nullable<int> crop, string achievement)
        {
            var estateParameter = estate != null ?
                new ObjectParameter("estate", estate) :
                new ObjectParameter("estate", typeof(string));
    
            var harvestDateParameter = harvestDate.HasValue ?
                new ObjectParameter("HarvestDate", harvestDate) :
                new ObjectParameter("HarvestDate", typeof(System.DateTime));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            var cropParameter = crop.HasValue ?
                new ObjectParameter("Crop", crop) :
                new ObjectParameter("Crop", typeof(int));
    
            var achievementParameter = achievement != null ?
                new ObjectParameter("Achievement", achievement) :
                new ObjectParameter("Achievement", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReport_Cetak_BukuPanenItem_Rev1_Result>("spReport_Cetak_BukuPanenItem_Rev1", estateParameter, harvestDateParameter, divisionParameter, gangParameter, cropParameter, achievementParameter);
        }
    
        public virtual ObjectResult<spReport_GetBukuPanenItemPenalty_Result> spReport_GetBukuPanenItemPenalty(string estate, string nik, Nullable<System.DateTime> harvestDate, string location, string crop, string achievement, string gang)
        {
            var estateParameter = estate != null ?
                new ObjectParameter("estate", estate) :
                new ObjectParameter("estate", typeof(string));
    
            var nikParameter = nik != null ?
                new ObjectParameter("Nik", nik) :
                new ObjectParameter("Nik", typeof(string));
    
            var harvestDateParameter = harvestDate.HasValue ?
                new ObjectParameter("HarvestDate", harvestDate) :
                new ObjectParameter("HarvestDate", typeof(System.DateTime));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var cropParameter = crop != null ?
                new ObjectParameter("Crop", crop) :
                new ObjectParameter("Crop", typeof(string));
    
            var achievementParameter = achievement != null ?
                new ObjectParameter("Achievement", achievement) :
                new ObjectParameter("Achievement", typeof(string));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReport_GetBukuPanenItemPenalty_Result>("spReport_GetBukuPanenItemPenalty", estateParameter, nikParameter, harvestDateParameter, locationParameter, cropParameter, achievementParameter, gangParameter);
        }
    
        public virtual ObjectResult<spReport_POTONGBUAH_HDR_Result> spReport_POTONGBUAH_HDR(Nullable<System.DateTime> start, Nullable<System.DateTime> finish, string estate, string gang, string nik)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var finishParameter = finish.HasValue ?
                new ObjectParameter("Finish", finish) :
                new ObjectParameter("Finish", typeof(System.DateTime));
    
            var estateParameter = estate != null ?
                new ObjectParameter("Estate", estate) :
                new ObjectParameter("Estate", typeof(string));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            var nikParameter = nik != null ?
                new ObjectParameter("Nik", nik) :
                new ObjectParameter("Nik", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReport_POTONGBUAH_HDR_Result>("spReport_POTONGBUAH_HDR", startParameter, finishParameter, estateParameter, gangParameter, nikParameter);
        }
    
        public virtual ObjectResult<spReport_ANOMALI_Result> spReport_ANOMALI(string estate, Nullable<System.DateTime> date, string division)
        {
            var estateParameter = estate != null ?
                new ObjectParameter("estate", estate) :
                new ObjectParameter("estate", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReport_ANOMALI_Result>("spReport_ANOMALI", estateParameter, dateParameter, divisionParameter);
        }
    
        public virtual ObjectResult<spReport_CETAK_BUKUPANEN_HEADER_Online_Result> spReport_CETAK_BUKUPANEN_HEADER_Online(string eSTATE, Nullable<System.DateTime> hARVEST_DATE, string dIVISION, string gANG)
        {
            var eSTATEParameter = eSTATE != null ?
                new ObjectParameter("ESTATE", eSTATE) :
                new ObjectParameter("ESTATE", typeof(string));
    
            var hARVEST_DATEParameter = hARVEST_DATE.HasValue ?
                new ObjectParameter("HARVEST_DATE", hARVEST_DATE) :
                new ObjectParameter("HARVEST_DATE", typeof(System.DateTime));
    
            var dIVISIONParameter = dIVISION != null ?
                new ObjectParameter("DIVISION", dIVISION) :
                new ObjectParameter("DIVISION", typeof(string));
    
            var gANGParameter = gANG != null ?
                new ObjectParameter("GANG", gANG) :
                new ObjectParameter("GANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReport_CETAK_BUKUPANEN_HEADER_Online_Result>("spReport_CETAK_BUKUPANEN_HEADER_Online", eSTATEParameter, hARVEST_DATEParameter, dIVISIONParameter, gANGParameter);
        }
    
        public virtual ObjectResult<spReport_GetBukuPanenItemNormal_Result> spReport_GetBukuPanenItemNormal(string estate, string nik, Nullable<System.DateTime> harvestDate, string location, string crop, string achievement, string gang)
        {
            var estateParameter = estate != null ?
                new ObjectParameter("estate", estate) :
                new ObjectParameter("estate", typeof(string));
    
            var nikParameter = nik != null ?
                new ObjectParameter("Nik", nik) :
                new ObjectParameter("Nik", typeof(string));
    
            var harvestDateParameter = harvestDate.HasValue ?
                new ObjectParameter("HarvestDate", harvestDate) :
                new ObjectParameter("HarvestDate", typeof(System.DateTime));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var cropParameter = crop != null ?
                new ObjectParameter("Crop", crop) :
                new ObjectParameter("Crop", typeof(string));
    
            var achievementParameter = achievement != null ?
                new ObjectParameter("Achievement", achievement) :
                new ObjectParameter("Achievement", typeof(string));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReport_GetBukuPanenItemNormal_Result>("spReport_GetBukuPanenItemNormal", estateParameter, nikParameter, harvestDateParameter, locationParameter, cropParameter, achievementParameter, gangParameter);
        }
    
        public virtual ObjectResult<spReport_ANOMALIPANENVSANGKUT_Result> spReport_ANOMALIPANENVSANGKUT(Nullable<System.DateTime> start, Nullable<System.DateTime> finish, string block, string estate)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var finishParameter = finish.HasValue ?
                new ObjectParameter("Finish", finish) :
                new ObjectParameter("Finish", typeof(System.DateTime));
    
            var blockParameter = block != null ?
                new ObjectParameter("Block", block) :
                new ObjectParameter("Block", typeof(string));
    
            var estateParameter = estate != null ?
                new ObjectParameter("Estate", estate) :
                new ObjectParameter("Estate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReport_ANOMALIPANENVSANGKUT_Result>("spReport_ANOMALIPANENVSANGKUT", startParameter, finishParameter, blockParameter, estateParameter);
        }
    
        public virtual ObjectResult<spReport_Header_Result> spReport_Header(string estate)
        {
            var estateParameter = estate != null ?
                new ObjectParameter("estate", estate) :
                new ObjectParameter("estate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReport_Header_Result>("spReport_Header", estateParameter);
        }
    
        public virtual ObjectResult<spReport_PrestasiOutputHKDivisi_Result> spReport_PrestasiOutputHKDivisi(string estate, string divisi, Nullable<System.DateTime> bkmdate)
        {
            var estateParameter = estate != null ?
                new ObjectParameter("estate", estate) :
                new ObjectParameter("estate", typeof(string));
    
            var divisiParameter = divisi != null ?
                new ObjectParameter("divisi", divisi) :
                new ObjectParameter("divisi", typeof(string));
    
            var bkmdateParameter = bkmdate.HasValue ?
                new ObjectParameter("bkmdate", bkmdate) :
                new ObjectParameter("bkmdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReport_PrestasiOutputHKDivisi_Result>("spReport_PrestasiOutputHKDivisi", estateParameter, divisiParameter, bkmdateParameter);
        }
    
        public virtual ObjectResult<spReport_Signing_Result> spReport_Signing(string estate, Nullable<System.DateTime> bkmDate, string division, string gang)
        {
            var estateParameter = estate != null ?
                new ObjectParameter("estate", estate) :
                new ObjectParameter("estate", typeof(string));
    
            var bkmDateParameter = bkmDate.HasValue ?
                new ObjectParameter("BkmDate", bkmDate) :
                new ObjectParameter("BkmDate", typeof(System.DateTime));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReport_Signing_Result>("spReport_Signing", estateParameter, bkmDateParameter, divisionParameter, gangParameter);
        }
    
        public virtual ObjectResult<spReport_HeaderTaksasi_Result> spReport_HeaderTaksasi(string estate, string division, Nullable<int> year)
        {
            var estateParameter = estate != null ?
                new ObjectParameter("estate", estate) :
                new ObjectParameter("estate", typeof(string));
    
            var divisionParameter = division != null ?
                new ObjectParameter("division", division) :
                new ObjectParameter("division", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReport_HeaderTaksasi_Result>("spReport_HeaderTaksasi", estateParameter, divisionParameter, yearParameter);
        }
    
        public virtual ObjectResult<spReport_Taksasi_Result> spReport_Taksasi(string estate, string division, Nullable<int> year, Nullable<int> period, Nullable<System.DateTime> startdate, Nullable<System.DateTime> enddate)
        {
            var estateParameter = estate != null ?
                new ObjectParameter("estate", estate) :
                new ObjectParameter("estate", typeof(string));
    
            var divisionParameter = division != null ?
                new ObjectParameter("division", division) :
                new ObjectParameter("division", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var periodParameter = period.HasValue ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(int));
    
            var startdateParameter = startdate.HasValue ?
                new ObjectParameter("startdate", startdate) :
                new ObjectParameter("startdate", typeof(System.DateTime));
    
            var enddateParameter = enddate.HasValue ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReport_Taksasi_Result>("spReport_Taksasi", estateParameter, divisionParameter, yearParameter, periodParameter, startdateParameter, enddateParameter);
        }
    
        public virtual ObjectResult<spReport_GetBukuPanenItemNormal_JJG_Result> spReport_GetBukuPanenItemNormal_JJG(string estate, string nik, Nullable<System.DateTime> harvestDate, string location, string crop)
        {
            var estateParameter = estate != null ?
                new ObjectParameter("estate", estate) :
                new ObjectParameter("estate", typeof(string));
    
            var nikParameter = nik != null ?
                new ObjectParameter("Nik", nik) :
                new ObjectParameter("Nik", typeof(string));
    
            var harvestDateParameter = harvestDate.HasValue ?
                new ObjectParameter("HarvestDate", harvestDate) :
                new ObjectParameter("HarvestDate", typeof(System.DateTime));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var cropParameter = crop != null ?
                new ObjectParameter("Crop", crop) :
                new ObjectParameter("Crop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReport_GetBukuPanenItemNormal_JJG_Result>("spReport_GetBukuPanenItemNormal_JJG", estateParameter, nikParameter, harvestDateParameter, locationParameter, cropParameter);
        }
    
        public virtual ObjectResult<spReport_GetBukuPanenItemNormal_LSF_Result> spReport_GetBukuPanenItemNormal_LSF(string estate, string nik, Nullable<System.DateTime> harvestDate, string location, string crop)
        {
            var estateParameter = estate != null ?
                new ObjectParameter("estate", estate) :
                new ObjectParameter("estate", typeof(string));
    
            var nikParameter = nik != null ?
                new ObjectParameter("Nik", nik) :
                new ObjectParameter("Nik", typeof(string));
    
            var harvestDateParameter = harvestDate.HasValue ?
                new ObjectParameter("HarvestDate", harvestDate) :
                new ObjectParameter("HarvestDate", typeof(System.DateTime));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var cropParameter = crop != null ?
                new ObjectParameter("Crop", crop) :
                new ObjectParameter("Crop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReport_GetBukuPanenItemNormal_LSF_Result>("spReport_GetBukuPanenItemNormal_LSF", estateParameter, nikParameter, harvestDateParameter, locationParameter, cropParameter);
        }
    
        public virtual ObjectResult<spReport_GetBukuPanenItemNormal_SUM_Result> spReport_GetBukuPanenItemNormal_SUM(string estate, string nik, Nullable<System.DateTime> harvestDate, string location, string crop, string achievement, string gang)
        {
            var estateParameter = estate != null ?
                new ObjectParameter("estate", estate) :
                new ObjectParameter("estate", typeof(string));
    
            var nikParameter = nik != null ?
                new ObjectParameter("Nik", nik) :
                new ObjectParameter("Nik", typeof(string));
    
            var harvestDateParameter = harvestDate.HasValue ?
                new ObjectParameter("HarvestDate", harvestDate) :
                new ObjectParameter("HarvestDate", typeof(System.DateTime));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var cropParameter = crop != null ?
                new ObjectParameter("Crop", crop) :
                new ObjectParameter("Crop", typeof(string));
    
            var achievementParameter = achievement != null ?
                new ObjectParameter("Achievement", achievement) :
                new ObjectParameter("Achievement", typeof(string));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReport_GetBukuPanenItemNormal_SUM_Result>("spReport_GetBukuPanenItemNormal_SUM", estateParameter, nikParameter, harvestDateParameter, locationParameter, cropParameter, achievementParameter, gangParameter);
        }
    
        public virtual int SPS_POTONGBUAH(Nullable<System.DateTime> start, Nullable<System.DateTime> finish, string gang, string nik)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var finishParameter = finish.HasValue ?
                new ObjectParameter("Finish", finish) :
                new ObjectParameter("Finish", typeof(System.DateTime));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            var nikParameter = nik != null ?
                new ObjectParameter("Nik", nik) :
                new ObjectParameter("Nik", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPS_POTONGBUAH", startParameter, finishParameter, gangParameter, nikParameter);
        }
    }
}
