//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.Report.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PPMSEntities : DbContext
    {
        public PPMSEntities()
            : base("name=PPMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblM_CheckrollPeriod> tblM_CheckrollPeriod { get; set; }
        public virtual DbSet<tblM_AccountingPeriod> tblM_AccountingPeriod { get; set; }
    
        public virtual ObjectResult<SPS_CETAK_BKMHK_Result> SPS_CETAK_BKMHK(Nullable<System.DateTime> bkmDate, string division, string gangCode)
        {
            var bkmDateParameter = bkmDate.HasValue ?
                new ObjectParameter("BkmDate", bkmDate) :
                new ObjectParameter("BkmDate", typeof(System.DateTime));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            var gangCodeParameter = gangCode != null ?
                new ObjectParameter("GangCode", gangCode) :
                new ObjectParameter("GangCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_CETAK_BKMHK_Result>("SPS_CETAK_BKMHK", bkmDateParameter, divisionParameter, gangCodeParameter);
        }
    
        public virtual ObjectResult<SPS_CETAK_BKMHK_DETAIL_DDT_Result> SPS_CETAK_BKMHK_DETAIL_DDT(Nullable<System.DateTime> bkmDate, string division, string gangCode)
        {
            var bkmDateParameter = bkmDate.HasValue ?
                new ObjectParameter("BkmDate", bkmDate) :
                new ObjectParameter("BkmDate", typeof(System.DateTime));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            var gangCodeParameter = gangCode != null ?
                new ObjectParameter("GangCode", gangCode) :
                new ObjectParameter("GangCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_CETAK_BKMHK_DETAIL_DDT_Result>("SPS_CETAK_BKMHK_DETAIL_DDT", bkmDateParameter, divisionParameter, gangCodeParameter);
        }
    
        public virtual ObjectResult<SPS_Cetak_BukuPanenItem_Result> SPS_Cetak_BukuPanenItem(Nullable<System.DateTime> harvestDate, string location, string division, string gang, Nullable<int> crop, string achievement)
        {
            var harvestDateParameter = harvestDate.HasValue ?
                new ObjectParameter("HarvestDate", harvestDate) :
                new ObjectParameter("HarvestDate", typeof(System.DateTime));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            var cropParameter = crop.HasValue ?
                new ObjectParameter("Crop", crop) :
                new ObjectParameter("Crop", typeof(int));
    
            var achievementParameter = achievement != null ?
                new ObjectParameter("Achievement", achievement) :
                new ObjectParameter("Achievement", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_Cetak_BukuPanenItem_Result>("SPS_Cetak_BukuPanenItem", harvestDateParameter, locationParameter, divisionParameter, gangParameter, cropParameter, achievementParameter);
        }
    
        public virtual ObjectResult<SPS_Cetak_BukuPanenItem_Quality_Result> SPS_Cetak_BukuPanenItem_Quality(Nullable<System.DateTime> harvestDate, string location, string division, string gang, Nullable<int> crop, string quality)
        {
            var harvestDateParameter = harvestDate.HasValue ?
                new ObjectParameter("HarvestDate", harvestDate) :
                new ObjectParameter("HarvestDate", typeof(System.DateTime));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            var cropParameter = crop.HasValue ?
                new ObjectParameter("Crop", crop) :
                new ObjectParameter("Crop", typeof(int));
    
            var qualityParameter = quality != null ?
                new ObjectParameter("Quality", quality) :
                new ObjectParameter("Quality", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_Cetak_BukuPanenItem_Quality_Result>("SPS_Cetak_BukuPanenItem_Quality", harvestDateParameter, locationParameter, divisionParameter, gangParameter, cropParameter, qualityParameter);
        }
    
        public virtual ObjectResult<SPS_CETAK_BKMHK_DETAIL_Result> SPS_CETAK_BKMHK_DETAIL(Nullable<System.DateTime> bkmDate, string division, string gangCode)
        {
            var bkmDateParameter = bkmDate.HasValue ?
                new ObjectParameter("BkmDate", bkmDate) :
                new ObjectParameter("BkmDate", typeof(System.DateTime));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            var gangCodeParameter = gangCode != null ?
                new ObjectParameter("GangCode", gangCode) :
                new ObjectParameter("GangCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_CETAK_BKMHK_DETAIL_Result>("SPS_CETAK_BKMHK_DETAIL", bkmDateParameter, divisionParameter, gangCodeParameter);
        }
    
        public virtual ObjectResult<SPS_CETAK_BUKUPANEN_HEADER_REV1_Result> SPS_CETAK_BUKUPANEN_HEADER_REV1(Nullable<System.DateTime> harvestDate, string division, string gang)
        {
            var harvestDateParameter = harvestDate.HasValue ?
                new ObjectParameter("HarvestDate", harvestDate) :
                new ObjectParameter("HarvestDate", typeof(System.DateTime));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_CETAK_BUKUPANEN_HEADER_REV1_Result>("SPS_CETAK_BUKUPANEN_HEADER_REV1", harvestDateParameter, divisionParameter, gangParameter);
        }
    
        public virtual ObjectResult<SPS_Cetak_BukuPanenItem_Rev1_Result> SPS_Cetak_BukuPanenItem_Rev1(Nullable<System.DateTime> harvestDate, string division, string gang, Nullable<int> crop, string achievement)
        {
            var harvestDateParameter = harvestDate.HasValue ?
                new ObjectParameter("HarvestDate", harvestDate) :
                new ObjectParameter("HarvestDate", typeof(System.DateTime));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            var cropParameter = crop.HasValue ?
                new ObjectParameter("Crop", crop) :
                new ObjectParameter("Crop", typeof(int));
    
            var achievementParameter = achievement != null ?
                new ObjectParameter("Achievement", achievement) :
                new ObjectParameter("Achievement", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_Cetak_BukuPanenItem_Rev1_Result>("SPS_Cetak_BukuPanenItem_Rev1", harvestDateParameter, divisionParameter, gangParameter, cropParameter, achievementParameter);
        }
    
        public virtual ObjectResult<GetBukuPanenItemNormal_Result> GetBukuPanenItemNormal(string nik, Nullable<System.DateTime> harvestDate, string location, string crop, string achievement, string gang)
        {
            var nikParameter = nik != null ?
                new ObjectParameter("Nik", nik) :
                new ObjectParameter("Nik", typeof(string));
    
            var harvestDateParameter = harvestDate.HasValue ?
                new ObjectParameter("HarvestDate", harvestDate) :
                new ObjectParameter("HarvestDate", typeof(System.DateTime));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var cropParameter = crop != null ?
                new ObjectParameter("Crop", crop) :
                new ObjectParameter("Crop", typeof(string));
    
            var achievementParameter = achievement != null ?
                new ObjectParameter("Achievement", achievement) :
                new ObjectParameter("Achievement", typeof(string));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBukuPanenItemNormal_Result>("GetBukuPanenItemNormal", nikParameter, harvestDateParameter, locationParameter, cropParameter, achievementParameter, gangParameter);
        }
    
        public virtual ObjectResult<GetBukuPanenItemPenalty_Result> GetBukuPanenItemPenalty(string nik, Nullable<System.DateTime> harvestDate, string location, string crop, string achievement, string gang)
        {
            var nikParameter = nik != null ?
                new ObjectParameter("Nik", nik) :
                new ObjectParameter("Nik", typeof(string));
    
            var harvestDateParameter = harvestDate.HasValue ?
                new ObjectParameter("HarvestDate", harvestDate) :
                new ObjectParameter("HarvestDate", typeof(System.DateTime));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var cropParameter = crop != null ?
                new ObjectParameter("Crop", crop) :
                new ObjectParameter("Crop", typeof(string));
    
            var achievementParameter = achievement != null ?
                new ObjectParameter("Achievement", achievement) :
                new ObjectParameter("Achievement", typeof(string));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBukuPanenItemPenalty_Result>("GetBukuPanenItemPenalty", nikParameter, harvestDateParameter, locationParameter, cropParameter, achievementParameter, gangParameter);
        }
    
        public virtual ObjectResult<SPS_POTONGBUAH_Result> SPS_POTONGBUAH(Nullable<System.DateTime> start, Nullable<System.DateTime> finish, string gang, string nik)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var finishParameter = finish.HasValue ?
                new ObjectParameter("Finish", finish) :
                new ObjectParameter("Finish", typeof(System.DateTime));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            var nikParameter = nik != null ?
                new ObjectParameter("Nik", nik) :
                new ObjectParameter("Nik", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_POTONGBUAH_Result>("SPS_POTONGBUAH", startParameter, finishParameter, gangParameter, nikParameter);
        }
    
        public virtual ObjectResult<SPS_POTONGBUAH_HDR_Result> SPS_POTONGBUAH_HDR(Nullable<System.DateTime> start, Nullable<System.DateTime> finish, string gang, string nik)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var finishParameter = finish.HasValue ?
                new ObjectParameter("Finish", finish) :
                new ObjectParameter("Finish", typeof(System.DateTime));
    
            var gangParameter = gang != null ?
                new ObjectParameter("Gang", gang) :
                new ObjectParameter("Gang", typeof(string));
    
            var nikParameter = nik != null ?
                new ObjectParameter("Nik", nik) :
                new ObjectParameter("Nik", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_POTONGBUAH_HDR_Result>("SPS_POTONGBUAH_HDR", startParameter, finishParameter, gangParameter, nikParameter);
        }
    
        public virtual ObjectResult<SP_PrestasiOuputHKDivisi_Result> SP_PrestasiOuputHKDivisi(string divisi, Nullable<System.DateTime> bkmdate)
        {
            var divisiParameter = divisi != null ?
                new ObjectParameter("divisi", divisi) :
                new ObjectParameter("divisi", typeof(string));
    
            var bkmdateParameter = bkmdate.HasValue ?
                new ObjectParameter("bkmdate", bkmdate) :
                new ObjectParameter("bkmdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PrestasiOuputHKDivisi_Result>("SP_PrestasiOuputHKDivisi", divisiParameter, bkmdateParameter);
        }
    
        public virtual ObjectResult<SPS_REPORT_ANOMALI_Result> SPS_REPORT_ANOMALI(Nullable<System.DateTime> date, string division)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var divisionParameter = division != null ?
                new ObjectParameter("Division", division) :
                new ObjectParameter("Division", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_REPORT_ANOMALI_Result>("SPS_REPORT_ANOMALI", dateParameter, divisionParameter);
        }
    
        public virtual ObjectResult<SPS_REPORTANOMALIPANENVSANGKUT_Result> SPS_REPORTANOMALIPANENVSANGKUT(Nullable<System.DateTime> start, Nullable<System.DateTime> finish, string block, string estate)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var finishParameter = finish.HasValue ?
                new ObjectParameter("Finish", finish) :
                new ObjectParameter("Finish", typeof(System.DateTime));
    
            var blockParameter = block != null ?
                new ObjectParameter("Block", block) :
                new ObjectParameter("Block", typeof(string));
    
            var estateParameter = estate != null ?
                new ObjectParameter("Estate", estate) :
                new ObjectParameter("Estate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_REPORTANOMALIPANENVSANGKUT_Result>("SPS_REPORTANOMALIPANENVSANGKUT", startParameter, finishParameter, blockParameter, estateParameter);
        }
    }
}
